$(".name p").html("<p>Личный кабинет - Терабит</p>");
$(".footer-copy").html("<p>ООО «Терабит» © 2018 Все права защищены</p>");
$(".footer-copy").css('margin','30px 0px');
$(".header").css('background','#009aff').css('border-bottom','none');
$('[href="/lbweb-client/api.php?r=profile/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=invoice/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=internet/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=dtv/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=phone/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=other/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=block/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=password/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=antivirus/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=helpdesk/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=sharedposts/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=helpdesk/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=helpdesk/kb"]').css('display','none');
$('[href="/lbweb-client/api.php?r=promo/index"]').css('display','none');
$('[href="/lbweb-client/api.php?r=payment/cards"]').css('display','none');
// $('[href="/lbweb-client/api.php?r=payment/yandex"]').css('display','none');
$('[href="/lbweb-client/api.php?r=payment/yandex"]').css('display','table-footer-group');
$('[href="/lbweb-client/api.php?r=payment/assist"]').css('display','none');
$('[href="/lbweb-client/api.php?r=payment/paymo"]').css('display','none');
$('[href="/lbweb-client/api.php?r=payment/payonline"]').css('display','none');
$('[href="/lbweb-client/api.php?r=payment/gazprom"]').css('display','none');
$('[href="/lbweb-client/api.php?r=payment/neoline"]').css('display','none');
$('[href="/lbweb-client/api.php?r=paysystems/chronopay"]').css('display','none');
$('[href="/lbweb-client/api.php?r=paysystems/moscow"]').css('display','none');
$('[href="/lbweb-client/api.php?r=paysystems/paymaster"]').css('display','none');
$('[href="/lbweb-client/api.php?r=paysystems/webmoney"]').css('display','none');
$('[href="/lbweb-client/api.php?r=paysystems/robokassa"]').css('display','none');
$('[href="/lbweb-client/api.php?r=paysystems/qiwi"]').css('display','none');
$('.notify-row').css('display','none');
$('.email-phone').css('display','none');
$('.loginblock p').css('display','none');
$('.loginblock hr').css('display','none');
$('.breadcrumb').css('display','none');
$('.breadcrumb:first-child').css('margin-top','7px');
$( ".breadcrumb" ).next( "em" ).css('display','none');
$( ".partition" ).css('display','table').css('width','100%');